{% set version = '4.4.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppparallel
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppParallel_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RcppParallel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppParallel/RcppParallel_{{ version }}.tar.gz
  sha256: ea893c69cbc16f980498cf0446813654d58642e9189d4b238274bb68ec5d67f8

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh >=1.60.0_1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh >=1.60.0_1

test:
  commands:
    - $R -e "library('RcppParallel')"           # [not win]
    - "\"%R%\" -e \"library('RcppParallel')\""  # [win]

about:
  home: http://rcppcore.github.io/RcppParallel, https://github.com/RcppCore/RcppParallel
  license: GPL-2
  summary: High level functions for parallel programming with 'Rcpp'. For example, the 'parallelFor()'
    function can be used to convert the work of a standard serial "for" loop into a
    parallel one and the 'parallelReduce()' function can be used for accumulating aggregate
    or other values.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
