{% set version = '4.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppparallel
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppParallel_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RcppParallel_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RcppParallel/RcppParallel_{{ version }}.tar.gz
  sha256: 018e7cbdf8c050e276e2f510d07aeb510d794e3478dba0f506d185a8ffac58be

build:
  merge_build_host: True  # [win]
  number: 1
  # compilation failed
  # cp: cannot stat 'tbb/build/lib_release/tbb*.dll': No such file or directory
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-bh >=1.60.0_1

  run:
    - r-base
    - r-bh >=1.60.0_1

test:
  commands:
    - $R -e "library('RcppParallel')"  # [not win]
    - "\"%R%\" -e \"library('RcppParallel')\""  # [win]

about:
  home: http://rcppcore.github.io/RcppParallel, https://github.com/RcppCore/RcppParallel
  license: GPL-2
  summary: High level functions for parallel programming with 'Rcpp'. For example, the 'parallelFor()'
    function can be used to convert the work of a standard serial "for" loop into a
    parallel one and the 'parallelReduce()' function can be used for accumulating aggregate
    or other values.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
