travis:
  secure:
    BINSTAR_TOKEN: wnsZWKVvhyquh9jnGEZipd8IU74WHnxXj0S0J80eO2KpRF4G3ru+eEePNLOleLNpCBbUwoHJAn08Yzt8RzCphuV8J2kMsQJYCn05ScE6KMalfwXrtrqAqy8TgKP9nivbm/mVhkXbbMTUdUbfaATH9CC2UWeb5eWTNI4BFdLATOAEMK+1JgYFVlizgrrXG9AYKi5nd1TnJY+tOKbH+9LM0wBbhQIHFJ6Yr0TT2UO+QWMDFSqo/okk43xcPjH2TXg+UBtWF4IxAyfLvzd9CHhKodwuCiV1cAr0mkn8ASv8nR5cxcvEnhwCspY7aJiP4AgyUMlE4jbmCnlcLncc7+T3H3QrN2jKj7iy7l+QFhUhlQGmwCJxpVyHFV4QkfUxCvUgbkeWGVzALAV9xmw07KAOJcBpy2r0HGwhbNmHzgdI0WGQ/asDKoc2FlY2UY3oQmor5BZftSlxxa1EcfmGCmRyZ7T1qzQmC+cvBoOqcy8U0/gJxX6ZgalyfYoY6TBfHtS9U0X9Aycfepm/vyVBA2y+BugnkIUQ6oDDGafkWPvgBMRkhRNYPgZVM6d9KomoIWAMRwvkEiEsjrUPhdTE1dbOeaMAfluAfIhjApV93Mcj681+444SsSJJmzHY7KLjeW2RvCkqxBgA/3YhH+xNzM74JkU0gYbA5tK1D8+S1r6FJzk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
