appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: oe0zYwkI/DnZn+p8NszbwVlF4Hab28dp2Q1GlhBI3dZfWnauC6vtyEhW+9ZvhwcVkpyBCPRCSe2SDQ295lOTYKnwDECcUJpAfNG+/8UEmVtBMkpYROWtA2mlYJxgbS+lfJAcVaNxehcvr14U0W+RltWnDIjx1uwybHy7polJRpGAV1JfT30SATWcJNiibh2sgkiXeB4BTUffryRvs2bG3DrvVsazXDQzd2Jd3EVmjKNj0vCzRggipoxKCGec7uBCVjL3ZvOru4yDJDJ9PgtRNO8LGHTx0fzsgJxnTagsBE1Z4FStbVcqAvV7Q/uXtywCvdUXoG6ij8ffjaB0JsNihlx8HNs4YCVwcKdvhv0Z+6Cd6FzWP0zcHNH1FGxPVa+/TZeuDXH0krn5ePc09MrInHUqwaLPMUOmP4zbtbjYp8VfRMyUsrqq2UTnbIRNBLREDyvbXv3avnSmkTtuaCj9GtFdSm3VrFkqL6oVl73lxY8+HMoS/xBATcaf9sUiGtzkPxaQRYOWXzzR/58gHFvvi9CzMAIhwadeDzyUW88y/Nzl+/EGtpHj+RQ+UyqAK8HNlRdm5IQP4n18U5BxgIieryQ2ABwnzbyFHwyTNuiS0k7Ewfx5PZpE1HfKspSzSYTyyfRav5JhbDq0MoMoEln59X4wy6icVuo1IzzUJVEh1Gk=}
